### PR TITLE
forward modelling examples for stormdb.process

### PR DESCRIPTION
**Pull request by cjayb**
Major changes include

* Freesufer- and SimNIBS-based pipelines for surface generation
* BEM and forward computations on the cluster

### CODE REVIEW

**Comment by RashaHyder** [comment]
I'm running into a problem when I try to extract the cortex.

When I run these commands:

sn = SimNIBS(proj_name=proj_name, output_dir=output_dir)

sn.mri2mesh(subject, t1_fs=t1_fs, t2_hb=t2_hb, t2mask=True,
            link_to_fs_dir=subjects_dir)

the output is:

0010_SHU
Converting DICOM to Nifti, this will take about 15 seconds...
...done.
Converting DICOM to Nifti, this will take about 15 seconds...
...done.
1 jobs created successfully, ready to submit.

but when I submit tho job to the cluster using sn.submit(), and then type qstat in the terminal it returns nothing!

The logfile says:

Executing following command on 1 threads:
mri2mesh --brain --subcort --head --t2mask 0010_SHU /projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/nifti/0010_SHU/t1_mprage_3D_sag_fatsat.nii.gz /projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/nifti/0010_SHU/t2_tse_sag_HighBW.nii.gz
/usr/local/common/GridEngine/default/spool/hyades06/job_scripts/3858276: line 23: mri2mesh: command not found
ln: failed to create symbolic link '/projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/fs_subjects_dir/0010_SHU': File exists
Done executing

**Comment by RashaHyder** [comment]
​I'm running into another problem when trying to create BEM surfaces. When I run these commands:

sn_bem = SimNIBS(proj_name=proj_name, output_dir=output_dir)
sn_bem.create_bem_surfaces?

sn_bem.create_bem_surfaces(subjects, make_coreg_head=True)

I have the jobs created and submitted to the cluster successfully: 
Processing multiple subjects:
0010_SHU
0011_UYX
2 jobs created successfully, ready to submit.
but when I checked the logfile here is what I found:

Executing following command on 1 threads:
meshfix /projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/m2m_0011_UYX/skull.stl -u 10 --vertices 5120 --fsmesh -o /projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/fs_0011_UYX/bem/simnibs/outer_skull
Reading dst volume...
Reading src volume...
MRISread(/projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/fs_0011_UYX/bem/simnibs/outer_skull.fsmesh): could not open file
No such file or directory
mris_transform: could not read surface file /projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/fs_0011_UYX/bem/simnibs/outer_skull.fsmesh
No such file or directory
rm: cannot remove '/projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/fs_0011_UYX/bem/simnibs/outer_skull.fsmesh': No such file or directory
meshfix /projects/MINDLAB2016_MEG-Language-PD-DBS/scratch/sn_subjects_dir/m2m_0011_UYX/skin.stl

**Comment by cjayb** [comment]
Hmm, I'll need more time to investigate all the things that seem to be going wrong...

**Comment by MadsJensen** [comment]
@cjayb it looks like the *.fsmesh is not in the dir but the files are named *.surf

**Pull request merged**
